### ISSUE TITLE
auth.Group.permissions: (fields.E304) Reverse accessor 'Permission.group_set'

### ISSUE THREAD

**Issue by matthewh** [ankitchhatbar/django-group-model#2] opened 2024-04-12 02:15 UTC
Greetings,

I'm encountering an error using this module to replace `auth.Group` when running makemigrations.. I'm following use case 1 and keeping the same name `group` .

```
❯ ENV=dev.local ./manage.py makemigrations sampleapp
SystemCheckError: System check identified some issues:

ERRORS:
auth.Group.permissions: (fields.E304) Reverse accessor 'Permission.group_set' for 'auth.Group.permissions' clashes with reverse accessor for 'sampleapp.Group.permissions'.
        HINT: Add or change a related_name argument to the definition for 'auth.Group.permissions' or 'sampleapp.Group.permissions'.
sampleapp.Group.permissions: (fields.E304) Reverse accessor 'Permission.group_set' for 'sampleapp.Group.permissions' clashes with reverse accessor for 'auth.Group.permissions'.
        HINT: Add or change a related_name argument to the definition for 'sampleapp.Group.permissions' or 'auth.Group.permissions'.
```

In settings.py

```
INSTALLED_APPS = [
    'django.contrib.admin',
    'django_group_model',  # must appear before any app providing user or groups
    'django.contrib.auth',
    ....
]

# https://pypi.org/project/django-group-model/
AUTH_GROUP_MODEL = 'sampleapp.Group'
```

In models.py

```
class Group(AbstractGroup):
    id = KsuidField(primary_key=True, prefix="group_")


class User(AbstractBaseUser, PermissionsMixin):

    id = KsuidField(primary_key=True, prefix="user_")

    groups = models.ManyToManyField(
        'sampleapp.Group',
        verbose_name=_("groups"),
        blank=True,
        help_text=_(
            "The groups this user belongs to. A user will get all permissions "
            "granted to each of their groups."
        ),
        related_name="user_set",
        related_query_name="user",
    )
```

Django 4.2, Python 3.10

What am I doing wrong?

**Comment by ankitchhatbar** [comment] 2024-04-12 21:41
Hi @matthewh,
Thanks for reporting this and detailed steps to reproduce it. It turns out that there are conflicts in the reverse accessor which is used when you want to access the Groups associated with a particular permission. 

A possible fix could be to change the reverse accessor of the Custom model from `group_set` to `custom_group_set`. With this, you would access groups attached to a permission using `permission.custom_group_set`.

This is only a problem if the custom model is called `Group`. If it is something else ([see docs here](https://github.com/ankitchhatbar/django-group-model?tab=readme-ov-file#customizing-the-name-of-the-group-model)), then it doesn't seem to be a problem

I will work on updating this and create a new release with the fix.

**Comment by matthewh** [comment] 2024-04-12 22:39
I see a potential issue in the Django ecosystem with a reliance on `django.contrib.auth.Group` across third party libraries. Your override for the ModelBackend during app initialization is a clever way to handle the permissions check against group.

But this example from [rest_framework_simplejwt](https://github.com/jazzband/djangorestframework-simplejwt/blob/c791e987332ed5e22a86428160d6372b1d85ffae/rest_framework_simplejwt/models.py#L27) is still likely to cause some issues in certain situations:
```
    _groups = EmptyManager(auth_models.Group)
    _user_permissions = EmptyManager(auth_models.Permission)
```

I found your library while researching existing methods for overriding permissions checks and Group. Now I'm thinking the only long term viable approach is a merge request against Django to add proper `AUTH_GROUP_MODEL` support. Unless you have some other clever suggestions to inject a custom model into `django.contrib.auth.models.Group`?

**Comment by ankitchhatbar** [comment] 2024-04-13 10:27
> But this example from [rest_framework_simplejwt](https://github.com/jazzband/djangorestframework-simplejwt/blob/c791e987332ed5e22a86428160d6372b1d85ffae/rest_framework_simplejwt/models.py#L27) is still likely to cause some issues in certain situations:

Yeah, there hasn't been a way that Django provides to decouple from the `auth.Group` model like the way you can decouple the `auth.User` model with `get_user_model()`. Libraries have been hard coding this dependency. Hence, it could be considered a limitation which will not work well with libraries that hard code the dependency to the Group model.

> Now I'm thinking the only long term viable approach is a merge request against Django to add proper `AUTH_GROUP_MODEL` support

This would be an ideal solution to the problem. There is also a [ticket](https://code.djangoproject.com/ticket/29748) for this and people are submitting patches to it for quite some time now, but it is marked as "wontfix".

We could create a `get_group_model()` which libraries can use to decouple from the `auth.Group` model. Libraries can depend on `django-group-model` for this. By default, if a custom group model has not been set, `get_group_model()` will return the default Django `Group` model. It could also be a feature for libraries because they can now support custom group models via this library.

**Closed as completed** 2024-04-14 10:46 UTC
